project:
  type: website
  output-dir: docs

website:
  title: "JK Capital"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Macro_Model.qmd
        text: Macro Model
      - text: Capital Markets
        menu:
          - href: screener.qmd
            text: Stock Screener
          - href: equity_research.qmd
            text: Equity Research
          - href: resources.qmd
            text: Resources
      - text: Sports
        menu:
          - href: EU_football.qmd
            text: European Football
          - href: MLB_baseball.qmd
            text: Major League Baseball

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    echo: false
    warning: false
    message: false

editor: source