project:
  type: website
  output-dir: docs

website:
  title: "Macro Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css

navbar:
  left:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: About
