project:
  type: website
  output-dir: docs

website:
  title: "Macro Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Macro_Model.qmd
        text: Macro Model

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css

