---
title: "About"
---

Thjk in a Snapshot...


## Education

Pomona College - Claremont, California, USA

+ Major in Economics and Minor in Mathematics


Chadwick International School - Incheon, South Korea

+ Full IB Diploma
+ Higer Levels: Language & Literature, Global Politics, History
+ Standard Levels: Biology, Math, Spanish


Dankook University Affiliate Middle School - Seoul, South Korea

+ 2 years of extremely rigorous grind at the hub of Korean education
+ Only-boys middle school
+ Endless hours of private academies (hagwons)


Daedo Elementary School - Seoul, South Korea

+ 5 years of extremely rigorous grind at the hub of Korean education
+ Endless hours of private academies (hagwons)
+ Lex Kim English School


Transit Middle School - Buffalo, New York, USA

+ Wonderful break from Korean education
+ A taste of cheerful life in US


Country Parkway Elementary School - Buffalo, New York, USA

+ Freedom from Korean education in a peaceful suburban New York


## Work Experience

Korea Search Fund

+ Crucial part of a live deal
+ Live buyout deal experience


Tortoise Capital Management

+ Developed a passion for value investing
+ Birth of a stock guru
+ Managing Partner Sull - now my lifelong mentor


Kim & Chang Law Firm

+ Experienced the challenges of M&A deals
+ Importance of connections in completing business deals


DoOne Accounting Corporation

+ Entire global financial system is powered by Excel
+ Work, Drink, Work more culture in Korea


## Activities & Achievements

Certified Investment Manager

+ Certified by Korean Financial Investment Association (KOFIA)


## Soccer Career

Daedo Elementary (2012-2013)

Dakook Middle (2014-2015)

Chadwick International Varsity Soccer (2016-2020)

Songdo FC (2015-2020)

Pomona-Pitzer Varsity Soccer (2020-2022)


## Military Experience

Republic of Korea Army - 2nd Corps Headquarters